version: "3.7"

services:
  validator:
    build: .
    image: odinprotocol/core:v0.7
    
    container_name: validator
    ports:
      - 26658:26658
      - 26657:26657
      - 26656:26656
      - 9090:9090
      - 1317:1317

    command: sh -c "odind start --rpc.laddr tcp://0.0.0.0:26657 --p2p.persistent_peers 492a4e30c10194e1d8f6fa194ba3f63b1aa73484@35.195.4.110:26656,417c2df701780c7f8751bc4a298411374082ef9e@34.78.138.110:26656,ea43cac04a556d01050a09a5699c3ba272a91116@34.78.239.23:26656,4edb332575e5108b131f0a7c0d9ac237569634ad@34.77.171.169:26656"
    
    volumes:
      - vol:/root/.odin
      - ./validator1/config:/root/.odin/config
      # - ./node_key.json:/root/.odin/config/node_key.json
      # - ./priv_validator_key.json:/root/.odin/config/priv_validator_key.json

  yoda:
    build: .
    image: odinprotocol/core:v0.7
    container_name: yoda
    depends_on:
     - validator

    restart: always
    command: sh -c "yoda run --log-level debug --node tcp://validator:26657"

    volumes:
     - ../.yoda:/root/.yoda

volumes:
  vol:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/16"
