// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: telemetry/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	github_com_cosmos_cosmos_sdk_x_bank_types "github.com/cosmos/cosmos-sdk/x/bank/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/QueryParams RPC
// method.
type QueryTopBalancesRequest struct {
	Denom      string             `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryTopBalancesRequest) Reset()         { *m = QueryTopBalancesRequest{} }
func (m *QueryTopBalancesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTopBalancesRequest) ProtoMessage()    {}
func (*QueryTopBalancesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4346fb254048dbbd, []int{0}
}
func (m *QueryTopBalancesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTopBalancesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTopBalancesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTopBalancesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTopBalancesRequest.Merge(m, src)
}
func (m *QueryTopBalancesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTopBalancesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTopBalancesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTopBalancesRequest proto.InternalMessageInfo

func (m *QueryTopBalancesRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *QueryTopBalancesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryParamsResponse is response type for the Query/QueryParams RPC
// method.
type QueryTopBalancesResponse struct {
	Balances []github_com_cosmos_cosmos_sdk_x_bank_types.Balance `protobuf:"bytes,1,rep,name=balances,proto3,casttype=github.com/cosmos/cosmos-sdk/x/bank/types.Balance" json:"balances"`
}

func (m *QueryTopBalancesResponse) Reset()         { *m = QueryTopBalancesResponse{} }
func (m *QueryTopBalancesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTopBalancesResponse) ProtoMessage()    {}
func (*QueryTopBalancesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4346fb254048dbbd, []int{1}
}
func (m *QueryTopBalancesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTopBalancesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTopBalancesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTopBalancesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTopBalancesResponse.Merge(m, src)
}
func (m *QueryTopBalancesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTopBalancesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTopBalancesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTopBalancesResponse proto.InternalMessageInfo

func (m *QueryTopBalancesResponse) GetBalances() []github_com_cosmos_cosmos_sdk_x_bank_types.Balance {
	if m != nil {
		return m.Balances
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryTopBalancesRequest)(nil), "telemetry.QueryTopBalancesRequest")
	proto.RegisterType((*QueryTopBalancesResponse)(nil), "telemetry.QueryTopBalancesResponse")
}

func init() { proto.RegisterFile("telemetry/query.proto", fileDescriptor_4346fb254048dbbd) }

var fileDescriptor_4346fb254048dbbd = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4f, 0x8b, 0xd3, 0x40,
	0x14, 0xcf, 0xac, 0xac, 0xb8, 0xd3, 0x5b, 0x58, 0xd9, 0x58, 0x96, 0xb4, 0x46, 0x90, 0x22, 0x74,
	0x86, 0x56, 0x2f, 0x5e, 0x83, 0xe8, 0x45, 0x44, 0x83, 0x27, 0x2f, 0x32, 0x49, 0x1e, 0x71, 0xd8,
	0x66, 0x5e, 0x36, 0x33, 0x75, 0xb7, 0x37, 0xf1, 0x0b, 0x28, 0xf8, 0xa5, 0xf6, 0xb8, 0xe0, 0xc5,
	0x53, 0x91, 0xd6, 0x4f, 0xe1, 0x49, 0x92, 0x99, 0xa6, 0x11, 0xff, 0x9c, 0x92, 0xbc, 0xf7, 0x7b,
	0xbf, 0x3f, 0xef, 0x85, 0xde, 0x36, 0xb0, 0x80, 0x12, 0x4c, 0xbd, 0xe2, 0xe7, 0x4b, 0xa8, 0x57,
	0xac, 0xaa, 0xd1, 0xa0, 0x7f, 0xd4, 0x95, 0x87, 0xc7, 0x05, 0x16, 0xd8, 0x56, 0x79, 0xf3, 0x66,
	0x01, 0xc3, 0xd3, 0x02, 0xb1, 0x58, 0x00, 0x17, 0x95, 0xe4, 0x42, 0x29, 0x34, 0xc2, 0x48, 0x54,
	0xda, 0x75, 0xc3, 0x0c, 0x75, 0x89, 0x9a, 0xa7, 0x42, 0x03, 0x7f, 0x3f, 0x4b, 0xc1, 0x88, 0x19,
	0xcf, 0x50, 0x2a, 0xd7, 0xbf, 0xfb, 0xb7, 0x7e, 0x2a, 0x16, 0x42, 0x65, 0xe0, 0x20, 0x0f, 0xfa,
	0x90, 0xd6, 0x5a, 0x07, 0xac, 0x44, 0x21, 0x55, 0xab, 0x67, 0xb1, 0xd1, 0x05, 0x3d, 0x79, 0xd5,
	0x20, 0x5e, 0x63, 0x15, 0x5b, 0x12, 0x9d, 0xc0, 0xf9, 0x12, 0xb4, 0xf1, 0x8f, 0xe9, 0x61, 0x0e,
	0x0a, 0xcb, 0x80, 0x8c, 0xc9, 0xe4, 0x28, 0xb1, 0x1f, 0xfe, 0x53, 0x4a, 0xf7, 0x24, 0xc1, 0xc1,
	0x98, 0x4c, 0x06, 0xf3, 0xfb, 0xcc, 0x2a, 0xb2, 0x46, 0x91, 0xd9, 0x65, 0x38, 0x45, 0xf6, 0x52,
	0x14, 0xe0, 0x18, 0x93, 0xde, 0x64, 0xf4, 0x89, 0xd0, 0xe0, 0x4f, 0x65, 0x5d, 0xa1, 0xd2, 0xe0,
	0x6b, 0x7a, 0xcb, 0x45, 0xd2, 0x01, 0x19, 0xdf, 0x98, 0x0c, 0xe6, 0xa7, 0xbf, 0x49, 0xec, 0xc8,
	0xdd, 0x60, 0xfc, 0xf8, 0x6a, 0x3d, 0xf2, 0x7e, 0xae, 0x47, 0xb3, 0x42, 0x9a, 0x77, 0xcb, 0x94,
	0x65, 0x58, 0x72, 0xb7, 0x04, 0xfb, 0x98, 0xea, 0xfc, 0x8c, 0x5f, 0xf2, 0x54, 0xa8, 0x33, 0x6e,
	0x56, 0x15, 0xe8, 0xdd, 0x68, 0xd2, 0x09, 0xcd, 0x3f, 0x10, 0x7a, 0xd8, 0x3a, 0xf2, 0x2f, 0xe8,
	0xa0, 0xe7, 0xca, 0x8f, 0x58, 0x77, 0x52, 0xf6, 0x8f, 0x65, 0x0d, 0xef, 0xfd, 0x17, 0x63, 0x63,
	0x45, 0xa3, 0x8f, 0x5f, 0x7f, 0x7c, 0x39, 0xb8, 0xe3, 0x9f, 0xf0, 0xfd, 0xaf, 0x63, 0xb0, 0x7a,
	0xbb, 0xb3, 0x10, 0xbf, 0xb8, 0xda, 0x84, 0xe4, 0x7a, 0x13, 0x92, 0xef, 0x9b, 0x90, 0x7c, 0xde,
	0x86, 0xde, 0xf5, 0x36, 0xf4, 0xbe, 0x6d, 0x43, 0xef, 0xcd, 0xa3, 0x5e, 0xb2, 0x67, 0x80, 0x4f,
	0xe2, 0xe9, 0x73, 0x59, 0x4a, 0x03, 0x39, 0xc7, 0x5c, 0xaa, 0x69, 0x86, 0x35, 0xf0, 0xcb, 0x3e,
	0x6d, 0x13, 0x32, 0xbd, 0xd9, 0x1e, 0xf9, 0xe1, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x04, 0x48,
	0x8d, 0x5f, 0xab, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// TopBalances returns all the system balances for specific denom.
	TopBalances(ctx context.Context, in *QueryTopBalancesRequest, opts ...grpc.CallOption) (*QueryTopBalancesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) TopBalances(ctx context.Context, in *QueryTopBalancesRequest, opts ...grpc.CallOption) (*QueryTopBalancesResponse, error) {
	out := new(QueryTopBalancesResponse)
	err := c.cc.Invoke(ctx, "/telemetry.Query/TopBalances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// TopBalances returns all the system balances for specific denom.
	TopBalances(context.Context, *QueryTopBalancesRequest) (*QueryTopBalancesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) TopBalances(ctx context.Context, req *QueryTopBalancesRequest) (*QueryTopBalancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TopBalances not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_TopBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTopBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TopBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/telemetry.Query/TopBalances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TopBalances(ctx, req.(*QueryTopBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TopBalances",
			Handler:    _Query_TopBalances_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "telemetry/query.proto",
}

func (m *QueryTopBalancesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTopBalancesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTopBalancesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTopBalancesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTopBalancesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTopBalancesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Balances) > 0 {
		for iNdEx := len(m.Balances) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Balances[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryTopBalancesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTopBalancesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Balances) > 0 {
		for _, e := range m.Balances {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryTopBalancesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTopBalancesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTopBalancesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTopBalancesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTopBalancesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTopBalancesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balances", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Balances = append(m.Balances, github_com_cosmos_cosmos_sdk_x_bank_types.Balance{})
			if err := m.Balances[len(m.Balances)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
