name: Build Workflow
on: [push, pull_request, workflow_dispatch]

jobs:
  core-build:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker container with ref
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.ci
          push: true
          tags: odinprotocol/core:${{ env.GITHUB_REF_SLUG }}

      - name: Build and push docker container latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.static
          push: true
          tags: odinprotocol/core:latest



