name: Tests
on: push

jobs:
  chain-test:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22.0"

      - name: Check go mod cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-chain-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-chain-

      - name: Run chain tests
        run: go test ./...
